version: 2

jobs:
   ubuntu18:
     # Ubuntu 18
     docker:
       - image: ubuntu:18.04
     steps:
       - checkout
       - run: |
          ls act/lang
          apt-get -q update -y
          apt-get -q install -y libedit-dev zlib1g-dev m4 build-essential cmake
          mkdir install
          export VLSI_TOOLS_SRC=`pwd`
          export ACT_HOME=$VLSI_TOOLS_SRC/install
          ./build.sh
          echo "done build step"
          ./test.sh

   centos8:
     docker:
       - image: centos:8
     steps:
       - checkout
       - run: |
          yum install -y 'dnf-command(config-manager)'
          yum config-manager --set-enabled powertools -y
          yum install -y gcc gcc-c++ diffutils make libedit-devel zlib-devel m4 cmake
          mkdir install
          export VLSI_TOOLS_SRC=`pwd`
          export ACT_HOME=$VLSI_TOOLS_SRC/install
          ./build.sh
          ./test.sh
          


workflows:
   version: 2
   build:
     jobs: 
        - ubuntu18
        - centos8

